# Generated by Django 3.1.5 on 2021-01-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_auto_20210126_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='data6',
            new_name='dateAJ',
        ),
    ]
