# Generated by Django 3.1.5 on 2021-01-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20210126_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='dateAJ',
        ),
    ]
